<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
      integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

<style>
    .grid {
        display: grid;
        grid-template-rows: 80px 80px;
        grid-template-columns: 185px 1fr 1fr 185px;
        grid-gap: 3px;
    }

    #grid > div {
        padding: .5em;
        text-align: center;
    }

    #item1 {
        grid-row-start: 1;
        grid-column-start: 1;
        grid-row-end: 2;
        grid-column-end: 5;
        background-color: #eceef6;
        text-align: center;
    }

    #item2 {
        grid-row-start: 2;
        grid-column-start: 1;
        grid-row-end: 2;
        grid-column-end: 5;
        background-color: white;
    }

    #item3 {
        grid-row-start: 3;
        grid-column-start: 1;
        grid-row-end: 4;
        grid-column-end: 2;
        background-color: #eceef6;
    }

    #item4 {
        grid-row-start: 3;
        grid-column-start: 2;
        grid-row-end: 4;
        grid-column-end: 4;
        background-color: white;
    }

    #item5 {
        grid-row-start: 3;
        grid-column-start: 4;
        grid-row-end: 4;
        grid-column-end: 5;
        background-color: #eceef6;
    }

    #item6 {
        grid-row-start: 4;
        grid-column-start: 1;
        grid-row-end: 5;
        grid-column-end: 3;
        background-color: white;
    }

    #item7 {
        grid-row-start: 4;
        grid-column-start: 3;
        grid-row-end: 5;
        grid-column-end: 5;
        background-color: #eceef6;
    }

    #item8 {
        grid-row-start: 5;
        grid-column-start: 1;
        grid-row-end: 10;
        grid-column-end: 5;
        background-color: white;
    }


</style>
<div class="grid">
    <div id="item1"><h2>Cardiff</h2></div>
    <div id="item2">Winners of the Groomswear Collection of the Year award 2019 for the second year running at The
        British
        Wedding Awards.
    </div>
    <div id="item3">
        <div class="left layout-column"><h3>Address</h3>
            <p>St David's Centre, 2 Hills Street, Cardiff, CF10 2LE</p>
            <p>02920 667480</p>
            <h3>Standard Opening Hours</h3>
            <p>Monday: 09:00 - 18:00</p>
            <p>Tuesday: 09:00 - 18:00</p>
            <p>Wednesday: 09:00 - 18:00</p>
            <p>Thursday: 09:00 - 19:30</p>
            <p>Friday: 09:00 - 18:00</p>
            <p>Saturday: 09:00 - 18:00</p>
            <p>Sunday: 10:30 - 16:30</p>
            <h3>Christmas Bank Holiday</h3>
            <p>Bank Holiday: 27th May - 10:30 - 17:00</p>
        </div>
    </div>
    <div id="item4">
        <div id="stores-map" style="width:auto; height: auto; position: relative; overflow: hidden;">
            <div style="overflow:hidden;width:auto;position: relative;">
                <iframe width="auto" height="450"
                        src="https://maps.google.com/maps?width=400&amp;height=450&amp;hl=en&amp;q=Akademika%20Proskury%20St%2C%201%2C%20Kharkiv+(Ronis)&amp;ie=UTF8&amp;t=&amp;z=11&amp;iwloc=B&amp;output=embed"
                        frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
                <div style="position: absolute;width: 80%;bottom: 5px;left: 0;right: 0;margin-left: auto;margin-right: auto;color: #000;text-align: center;">
                    <small style="line-height: 1.8;font-size: 2px;background: #fff;">Powered by <a
                                href="https://embedgooglemaps.com/ru/">embedgooglemaps RU</a> & <a
                                href="https://iamsterdamcard.it">iamsterdamcard</a></small>
                </div>
                <style>#gmap_canvas img {
                        max-width: none !important;
                        background: none !important
                    }</style>
            </div>
        </div>
    </div>
    <div id="item5">
        <div class="manager-photo">
            <picture>
                <!--[if IE 9]>
                <audio><![endif]-->
                <source media="(min-width: 150px)" sizes="121px"
                        data-srcset="https://www.slaters.co.uk/media/adminforms/cms_page/cache/1/store_manager_photo/121x131/5e06319eda06f020e43594a9c230972d/c/a/cardiff.jpg 121w, https://www.slaters.co.uk/media/adminforms/cms_page/cache/1/store_manager_photo/242x262/5e06319eda06f020e43594a9c230972d/c/a/cardiff.jpg 242w"
                        srcset="https://www.slaters.co.uk/media/adminforms/cms_page/cache/1/store_manager_photo/121x131/5e06319eda06f020e43594a9c230972d/c/a/cardiff.jpg 121w, https://www.slaters.co.uk/media/adminforms/cms_page/cache/1/store_manager_photo/242x262/5e06319eda06f020e43594a9c230972d/c/a/cardiff.jpg 242w">
                <source media="(min-width: 768px)" sizes="100vw"
                        data-srcset="https://www.slaters.co.uk/media/adminforms/cms_page/cache/1/store_manager_photo/97x105/5e06319eda06f020e43594a9c230972d/c/a/cardiff.jpg 768w, https://www.slaters.co.uk/media/adminforms/cms_page/cache/1/store_manager_photo/194x210/5e06319eda06f020e43594a9c230972d/c/a/cardiff.jpg 194w"
                        srcset="https://www.slaters.co.uk/media/adminforms/cms_page/cache/1/store_manager_photo/97x105/5e06319eda06f020e43594a9c230972d/c/a/cardiff.jpg 768w, https://www.slaters.co.uk/media/adminforms/cms_page/cache/1/store_manager_photo/194x210/5e06319eda06f020e43594a9c230972d/c/a/cardiff.jpg 194w">
                <source sizes="121px"
                        data-srcset="https://www.slaters.co.uk/media/adminforms/cms_page/cache/1/store_manager_photo/121x131/5e06319eda06f020e43594a9c230972d/c/a/cardiff.jpg 121w, https://www.slaters.co.uk/media/adminforms/cms_page/cache/1/store_manager_photo/242x262/5e06319eda06f020e43594a9c230972d/c/a/cardiff.jpg 242w"
                        srcset="https://www.slaters.co.uk/media/adminforms/cms_page/cache/1/store_manager_photo/121x131/5e06319eda06f020e43594a9c230972d/c/a/cardiff.jpg 121w, https://www.slaters.co.uk/media/adminforms/cms_page/cache/1/store_manager_photo/242x262/5e06319eda06f020e43594a9c230972d/c/a/cardiff.jpg 242w">
                <!--[if IE 9]></audio><![endif]-->
                <img class="picture-image lazyloaded" alt="Craig Moody"
                     src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==">
            </picture>

            <div class="manager-name">
                <h3>Store manager</h3>
                <span>Craig Moody</span>
            </div>
            <br>
            <ul>
                <li class="fa fa-info-circle"> <b>Assistant Manager</b>
                    <br>
                    <span>Ruth Rogers</span>
                </li>

                <li class="fas fa-wifi"> <b>WiFi</b><br>
                </li>

                <li class="fab fa-accessible-icon"> <b>Wheel Chair Access</b><br>
                </li>

                <li class="far fa-caret-square-up"> <b>Lift Location</b><br>
                    <span>Main Entrance</span>
                </li>

                <li class="fas fa-shopping-bag"> <b>Click &amp; Collect Location</b><br>
                    <span>Cash Desk</span>
                </li>
            </ul>
        </div>
    </div>
    <div id="item6"><h2 class="caption">Cardiff</h2>
        <div class="content">
            <p>Our Cardiff store is located on Hill Street, near the entrance to St David’s Centre. The
                store is under a 10-minute walk from both Cardiff Central and Cardiff Queen Street stations.<br><br>Opened
                in 1999, in St Mary's Street it moved in 2009 to its current location. The store is run by
                Craig Moody and his team of amazing staff who are there to assist you in the store.&nbsp;
            </p>
            <p><em><strong>Community Spirit</strong></em><b><i><br></i></b>The store is proud to be part of
                the community and has a great relationship with businesses, sports clubs and charities in
                the Cardiff area.&nbsp;<br><br><em><b><strong>Tailoring for all occasions&nbsp;</strong><br></b></em>Suits
                from 24” to 60” chest in a range of fits for all occasions; proms, weddings, graduations and
                business with free alterations. Our tailoring collection extends to beautifully tailored
                blazers, trousers and chinos from a range of well-known brands.<br><br><em><b><strong>Llongyfarchiadau/Congratulations</strong><br></b></em>Slater
                Menswear Cardiff is part of the national team who which Groomswear Collection of the Year at
                the British Wedding Awards 2019, for the second year running. They are also finalists at the
                Welsh National Wedding Awards.</p>
            <p><strong><em>What's in store</em><em><br></em></strong>-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span
                        style="color: #3366ff;"><a href="https://www.slaters.co.uk/mens-suits"
                                                   target="_self"><span
                                style="color: #3366ff;">Men’s Suits</span></a></span><br>-&nbsp;&nbsp;&nbsp;&nbsp;<span
                        style="color: #3366ff;">&nbsp;&nbsp;&nbsp;<a
                            href="https://www.slaters.co.uk/mens-blazers" target="_self"><span
                                style="color: #3366ff;">Blazers</span></a></span><br>-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span
                        style="color: #3366ff;"><a href="https://www.slaters.co.uk/mens-trousers"
                                                   target="_self"><span
                                style="color: #3366ff;">Trousers</span></a></span><br>-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span
                        style="color: #3366ff;"><a href="https://www.slaters.co.uk/mens-shoes"
                                                   target="_self"><span style="color: #3366ff;">Shoes</span></a> </span>and
                <span style="color: #3366ff;"><a href="https://www.slaters.co.uk/accessories-home"
                                                 target="_self"><span
                                style="color: #3366ff;">Accessories</span></a></span><br>-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span
                        style="color: #3366ff;"><a href="https://www.slaters.co.uk/casualwear-home"
                                                   target="_self"><span
                                style="color: #3366ff;">Casualwear</span></a></span><br>-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span
                        style="color: #3366ff;"><a
                            href="https://www.slaters.co.uk/slaters-formal-hire/cardiff"
                            target="_self"><span
                                style="color: #3366ff;">Formal hire</span></a>
                </span>
                <br><br>
                <span
                        style="text-decoration: underline;"><strong>Brands we stock</strong>
                </span><b>
                    <span
                            style="text-decoration: underline;"><br>
                    </span>
                </b>Ted Baker, Aquascutum, Magee,
                Wrangler, Barbour, Levi’s, Loakes, Steptronic, Justin Reece, Lambretta, Meyer and many more.<br><br>Head
                to the Cardiff store today for unbeatable customer service and free alterations in store.
                &nbsp;</p>
        </div>
    </div>
    <div id="item7">
        <div class="promo layout-column">
            <h2 class="caption">Awards</h2>
            <ul class="content">
                <li>
                    <div class="img-wrap">
                        <img src="https://www.slaters.co.uk/media/adminforms/store_awards_grid/cache/1/cache/400x405/8a02aedcaf38ad3a98187ab0a1dede95/g/r/groomswear-collection_1.jpg"
                             width="250" height="250" alt="" title="">
                    </div>
                    <h2>British Wedding Awards 2019 </h2>
                    <p>Winners of Groomswear Collection of the Year at The British Wedding Awards for the second
                        year running.</p>
                </li>
            </ul>
        </div>
    </div>

    <div id="item8">
        <div style="text-align: center"><h2>Browse our Store</h2></div>
        <iframe src="https://www.google.com/maps/embed?pb=!1m0!3m2!1sen!2sus!4v1469620467654!6m8!1m7!1s-mkeJVE4TCsAAAQWiOq3MA!2m2!1d51.47982348387283!2d-3.175727561963186!3f135!4f0!5f0.8160813932612223"
                width="100%" height="375" frameborder="0" style="border:0" allowfullscreen=""></iframe>
    </div>

    <script type="text/javascript">
        //<![CDATA[
        StoreLocatorDetail.apiKey = 'AIzaSyDwWzH9Z6RMGc4zIscXUPbrHIOaVgpW8u0	';
        StoreLocatorDetail.lat = 51.479212;
        StoreLocatorDetail.lng = -3.175179;
        StoreLocatorDetail.skinUrl = 'https://www.slaters.co.uk/skin/frontend/enterprise/slaters/';
        StoreLocatorDetail.zoom = 14;
        StoreLocatorDetail.loadMap();
        //]]>
    </script>
</div>
</div>
